package codes

type ErrorCode string

const (
	// OK is returned on success.
	OK ErrorCode = "000"

	Transaction_Processing    ErrorCode = "001"
	Invalid_Amount_in_Request ErrorCode = "002"
	Transaction_reversed      ErrorCode = "003"
	// InvalidArgument indicates client specified an invalid argument.
	// Note that this differs from FailedPrecondition. It indicates arguments
	// that are problematic regardless of the state of the system
	InvalidArgument      ErrorCode = "004"
	InvalidRequest       ErrorCode = "005"
	InvalidVoidRequest   ErrorCode = "006"
	InvalidRefundRequest ErrorCode = "007"

	Invalid_Service_Header ErrorCode = "008"
	// Transaction_not_found

	// NotFound means some requested entity (e.g., file or directory) was
	// not found.
	//
	NotFound ErrorCode = "201"
	//	Duplicate Transaction Reference Number (Sale)/Transaction Not Found (Voids)

	Duplicate_reff ErrorCode = "202"
	// AlreadyExists means an attempt to create an entity failed because one
	// already exists.
	AlreadyExists   ErrorCode = "203"
	No_Sale_Found   ErrorCode = "204"
	No_Void_Found   ErrorCode = "205"
	No_Refund_Found ErrorCode = "206"

	OmaService_Not_Found ErrorCode = "404"
	// Transaction Already Voided
	Already_Voided ErrorCode = "601"
	//	Transaction Already Declined/ Completed
	Already_Delined   ErrorCode = "602"
	Already_Refunded  ErrorCode = "603"
	Already_Timed_Out ErrorCode = "604"
	//	Transaction Timeout on RPS
	TimeOut ErrorCode = "701"
	// Transaction Cancelled by RPS
	Cancelled ErrorCode = "702"

	SerialNumber_MissMatch           ErrorCode = "801"
	SerialNumber_Already_Exist       ErrorCode = "802"
	ClientId_MissMatch               ErrorCode = "803"
	ClientId_Already_Exist           ErrorCode = "804"
	Invalid_Txn_Type                 ErrorCode = "805"
	SerialNumber_Already_Exist_NoReg ErrorCode = "806"
	Terminal_Already_Exists          ErrorCode = "807"
	No_InvoiceNo                     ErrorCode = "808"
	Terminal_Missmatch               ErrorCode = "809"
	Mid_Mismatch                     ErrorCode = "810"
	Client_Reregister                ErrorCode = "811"
	TerminalId_Mapped                ErrorCode = "812"
	No_RRN                           ErrorCode = "813"
	No_TipAmount                     ErrorCode = "814"
	Terminal_Client_Exist            ErrorCode = "815"
	No_PaperRoll                     ErrorCode = "816"
	MerchantId_MissMatch             ErrorCode = "817"
	Invalid_Rereg                    ErrorCode = "818"

	// invalid header
	Invalid_Mid           ErrorCode = "831"
	Invalid_KeyVersion    ErrorCode = "832"
	Invalid_SecretKey     ErrorCode = "833"
	Invalid_ReregVal      ErrorCode = "834"
	InvalidHeaderDetails  ErrorCode = "817"
	Invalid_TerminalId    ErrorCode = "818"
	Invalid_client_Reg    ErrorCode = "819"
	Unverified_terminalid ErrorCode = "820"
	Invalid_aes_key       ErrorCode = "821"
	Empty_payload         ErrorCode = "822"
	Invalid_Enc_payload   ErrorCode = "823"
	Invalid_payload       ErrorCode = "824"
	Unverified_ClientID   ErrorCode = "825"
	Invalid_pos_reg       ErrorCode = "826"
	Encryption_error      ErrorCode = "827"
	Decryption_error      ErrorCode = "828"
	Invalid_rsa_key       ErrorCode = "829"
	Invalid_client_key    ErrorCode = "830"

	// Unexpected Error
	Unexpected_err ErrorCode = "999"

	// ResourceExhausted indicates some resource has been exhausted, perhaps
	// a per-user quota, or perhaps the entire file system is out of space.
	//
	// This error code will be generated when
	// out-of-memory and server overload situations, or when a message is
	// larger than the configured maximum size.
	ResourceExhausted ErrorCode = "501"
	Aborted           ErrorCode = "502"
	// Internal errors. Means some invariants expected by underlying
	// system has been broken. If you see one of these errors,
	// something is very broken.
	//
	// This error code will be generated by the gRPC framework in several
	// internal error conditions.
	Internal ErrorCode = "503"
	Declined ErrorCode = "504"

	// _maxCode = 16
)
